/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f2ccb869-2339-428c-94e4-a2e228be52cb",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_eMyNy0DYI",
    "aws_user_pools_web_client_id": "6rjs8kict542cr9eqbihej0ag5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dq6gwg22qfarjiaewvklwb63em.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rgqf7libxzdhjfcab6pmz4njhe",
    "aws_user_files_s3_bucket": "testamplifyappeababee3b7bb4c66a8f5533b152aa094184545-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
